### ISSUE TITLE
Will this source code be released?

### ISSUE THREAD

**Issue by canglangzhige** [KennyChen880127/Implementation-of-a-Building-Advertising-System-using-Instance-Segmentation-and-Augmented-Reality#1]
Thanks for your work!
Will this source code be released?

**Comment by KennyChen880127** [comment]
> First of all, thank you for your recognition of my project. However, I regret to inform you that this project is considered laboratory property, so I am unable to provide the source code. Sorry for the inconvenience.

First of all, thank you for your recognition of my project. However, I regret to inform you that this project is considered laboratory property, so I am unable to provide the source code. Sorry for the inconvenience.

**Comment by KennyChen880127** [comment]
> Thanks for your work! Will this source code be released?

First of all, thank you for your recognition of my project. However, I regret to inform you that this project is considered laboratory property, so I am unable to provide the source code. Sorry for the inconvenience.
